apiVersion: apps/v1 
kind: Deployment
metadata:
  name: example-app1
  labels: 
     app: regapp

spec:
  replicas: 2 
  selector:
    matchLabels:
      app: regapp

  template:
    metadata:
      labels:
        app: regapp
    spec:
      containers:
      - name: regapp
        image: https://fisdemo1.jfrog.io/fis-demo-dockerhub-docker-local/hello-world.17:latest
        #image: nagarjunacse02/test-image.59
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
