apiVersion: apps/v1 
kind: Deployment
metadata:
  name: example-app1
  labels: 
     app: regapp
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: regapp
  template:
    metadata:
      labels:
        app: regapp
    spec:
      containers:
      - name: regapp
        #image: fisdemo1.jfrog.io/fis-demo-dockerhub-docker-local/hello-world.17
        image: nagarjunacse02/petclinic_app.24:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always  # Set image pull policy explicitly
      imagePullSecrets:  
      - name: artifactory-credentials
 
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
